name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 1 * *" # Run monthly on the 1st of each month

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      # - name: Run OWASP Dependency-Check
      #   run: ./gradlew dependencyCheckAnalyze
      # - name: Upload OWASP report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dependency-check-report
      #     path: app/build/reports/dependency-check-report.html
      #     retention-days: 7
